language: python
sudo: required
python: 3.6

env:
  - DJANGO_SETTINGS_MODULE=example.testapp.settings

install:
  - pip3 install -r example/requirements.txt

script:
  - cd example && python manage.py test

branches:
  only:
    - master

notifications:
  email: false
